stream {
    log_format db_gateway '$remote_addr [$time_local] '
                          '$protocol $status $bytes_sent $bytes_received '
                          '$session_time "$upstream_addr"';

    access_log /var/log/nginx/db-gateway-access.log db_gateway;
    error_log  /var/log/nginx/db-gateway-error.log warn;

    server {
        listen 51032;
        proxy_pass 127.0.0.1:50003;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }

    server {
        listen 51033;
        proxy_pass 127.0.0.1:50005;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }

    server {
        listen 51034;
        proxy_pass 127.0.0.1:50006;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }

    server {
        listen 51035;
        proxy_pass 127.0.0.1:50004;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }
}
